in_node_feats: 80
in_edge_feats: 13
node_out_feats: 320
edge_hidden_feats: 64
num_step_message_passing: 6
attention_heads: 8
attention_layers: 1
AtomTemplate_n: 21968
BondTemplate_n: 8033
model_file: models/LocalRetro/saved/LocalRetro_USPTO_479k.pth